version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - echo "Entered the install phase..."
      - ls -la
      - cd pkgs && zip -q ../function.zip -r9 . && cd .. && zip -qg function.zip getpondus.py
  build:
    commands:
      - echo "Entered the build phase..."
      - aws s3 cp function.zip s3://mclonberg-build-artifacts/pondus/
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
  