version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8

  build:
    commands:
      - echo "Entered the build phase..."
      - cd GetPondus
      - cd pkgs && zip -q ../function.zip -r9 . && cd .. && zip -qg function.zip getpondus.py
      - export BUCKET=mclonberg-build-artifacts
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --s3-prefix pondus --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - GetPondus/template.yml
    - GetPondus/outputtemplate.yml
  